### ISSUE TITLE
Module 2 - Google Map Embed

### ISSUE THREAD

**Issue by megansoh** [longcao/wedding#3]
If possible, make Google Map embed the same aspect ratio as half the screen split vertically.

<img width="960" alt="screen shot 2017-04-01 at 7 10 42 pm" src="https://cloud.githubusercontent.com/assets/13702084/24583141/f03e74da-170e-11e7-9617-7a8926336641.png">

**Comment by longcao** [comment]
Completed with https://github.com/longcao/wedding/commit/022c6425da75bd3da061125da32b45ca44e3dcfa.
