### ISSUE TITLE
Module 2 - Content

### ISSUE THREAD

**Issue by megansoh** [longcao/wedding#4]
H1:
Location

H3:
TIME: TBD
SATURDAY, OCTOBER 14, 2017

H4:
1770 EUCLID STREET NORTHWEST
WASHINGTON, DC 20009

If possible, add LINE logo as pictured: https://www.dropbox.com/s/ua8nnjvzitx8tut/LINE_logos-03.eps?dl=0

<img width="960" alt="screen shot 2017-04-01 at 7 10 42 pm" src="https://cloud.githubusercontent.com/assets/13702084/24583144/ff7e8a8e-170e-11e7-98e4-d27b8a6911aa.png">

**Comment by longcao** [comment]
Completed with https://github.com/longcao/wedding/commit/022c6425da75bd3da061125da32b45ca44e3dcfa.
