### ISSUE TITLE
Module 3 - Accommodations Content

### ISSUE THREAD

**Issue by megansoh** [longcao/wedding#7]
Header: Stay & Rest

Image: https://www.dropbox.com/s/615p1fyx28bp20s/sydell-dc-1.jpg?dl=0

Copy: 
for your comfort and convenience, we have reserved a
block of rooms at a discounted rate for friday and
saturday nights at the wedding venue, the line hotel.

district double queen - $239/night
district queen suite - $239/night

reserve by september 15th
        http://fontawesome.io/icon/phone/  202.588.0525 (can you make this so when you click the number, it prompts a phone call?)
         [helinehoteldc.com](http://bit.ly/2otcN2I) 

when booking, please use code 171012sohc or
reference the soh-cao wedding.

_sharing a room?_ be sure to mention their names.

if you’re extending your stay beyond these days
or want a room upgrade, [let us know](emailto: meganandlong@gmail.com)!

<img width="962" alt="screen shot 2017-04-09 at 5 20 23 pm" src="https://cloud.githubusercontent.com/assets/13702084/24841058/e09cd6bc-1d48-11e7-94f9-8a85cd3a05d0.png">

**Comment by megansoh** [comment]
"thelinehoteldc.com" should link to http://bit.ly/2otcN2I

**Comment by longcao** [comment]
First pass: https://github.com/longcao/wedding/commit/9557d177e91b8b0a6de5ddae2f069cd072709f8d.
