### ISSUE TITLE
Module 1 - Add Image

### ISSUE THREAD

**Issue by megansoh** [longcao/wedding#8]
Add image to the left side: https://www.dropbox.com/s/mbavj2z7s80h6ce/Vicki_Grafton_Photography-1-8.jpg?dl=0
or https://www.dropbox.com/s/6iwbbqgli4v0856/Vicki_Grafton_Photography-1-11.jpg?dl=0

<img width="961" alt="screen shot 2017-04-08 at 11 54 39 am" src="https://cloud.githubusercontent.com/assets/13702084/24830364/b08615c0-1c52-11e7-842d-bcb0df452e50.png">

**Comment by longcao** [comment]
Completed with https://github.com/longcao/wedding/commit/52b6a26b924bba3b87f01b30447b5184ba099173.
