### ISSUE TITLE
Module 4 - To & From

### ISSUE THREAD

**Issue by megansoh** [longcao/wedding#9]
Header: To & From

Centered Image - let me know if you need me to resize: https://www.dropbox.com/s/vsj9bwagt8xw122/traveltimes.jpg?dl=0

Body Copy, centered:
H3: travel notes
H4: local airports and time in transit
to and from the hotel

we highly recommend using local taxis or rideshare apps (lyft/uber) for your airport commutes. once you've settled in to your hotel room, walking and enjoy!

<img width="959" alt="screen shot 2017-04-09 at 5 32 34 pm" src="https://cloud.githubusercontent.com/assets/13702084/24841172/ab3c3d2a-1d4b-11e7-91c6-c913165e6522.png">

**Comment by longcao** [comment]
First pass is at https://github.com/longcao/wedding/commit/b934e27ac84524860a0a2fcac5341ada250ae9de but we might need a higher res image _or_ an SVG if we can managed that (though I don't know how those really work in HTML).

**Comment by megansoh** [comment]
I can make a higher res image, but the image frame itself should be smaller as shown in the design.

**Comment by megansoh** [comment]
https://www.dropbox.com/s/pdiwjefegozwc0d/traveltimes.svg?dl=0

**Comment by megansoh** [comment]
try these:
https://www.dropbox.com/s/mlqxln9diryvpoz/traveltimes_v2.jpg?dl=0
https://www.dropbox.com/s/9rrq8i4004bc4ps/traveltimes_v2.png?dl=0
